name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
    - uses: pre-commit/action@v3.0.1

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.13"]
        include:
          - python-version: "3.10"
            requirements_file: requirements_minpandas.txt
          - python-version: "3.13"
            requirements_file: requirements_dev.txt

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'etc/${{matrix.requirements_file}}'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r etc/${{matrix.requirements_file}}
        pip install -e .
    - if: runner.os != 'Windows'
      name: Set up Python tzdata on Linux and macOS
      run: |
        PYTHONTZPATH=$(python -c "import os; print(os.path.dirname(os.__file__))")
        echo "PYTHONTZPATH=$PYTHONTZPATH" >> $GITHUB_ENV
    - if: runner.os == 'Windows'
      name: Set up Python tzdata on Windows
      run: |
        $PYTHONTZPATH = python -c "import os; print(os.path.dirname(os.__file__))"
        echo "PYTHONTZPATH=$PYTHONTZPATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - name: Test with pytest
      run: |
        pytest tests -n auto --dist loadscope
